# Generated by Django 6.0.3 on 2026-03-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('DRIVER', 'driver'), ('CUSTOMER', 'customer')], default='CUSTOMER', max_length=20),
        ),
    ]
