# Generated by Django 6.0.3 on 2026-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantVendor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('DRIVER', 'driver'), ('CUSTOMER', 'customer'), ('RESTAURANT', 'restaurant')], default='CUSTOMER', max_length=20),
        ),
    ]
