# Generated by Django 6.0.3 on 2026-03-27 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car')], default='bike', max_length=50)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('license_plate', models.CharField(blank=True, max_length=15)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lon', models.FloatField(blank=True, null=True)),
                ('ratings', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
